name: Deploy to App Engine

on:
  push:
    branches:
      - firebase-auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Authenticate with Google Cloud
        run: gcloud auth login

      - name: Install dependencies
        run: npm ci

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.APPLICATION_CREDENTIALS }}
