name: Deploy to App Engine

on:
  push:
    branches:
      - firebase-auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Google Cloud SDK
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/google-cloud-sdk
          key: ${{ runner.os }}-gcloud-${{ hashFiles('**/google-cloud-sdk/VERSION') }}

      - name: Authenticate with Google Cloud
        env:
          PRIVATE_KEY: ${{ secrets.APPLICATION_CREDENTIALS }}
        run: echo "$PRIVATE_KEY" | gcloud auth activate-service-account --key-file=- --project ${{ secrets.GCLOUD_PROJECT }}

      - name: Create App Engine application
        run: gcloud app create --quiet

      - name: Install dependencies
        run: npm ci

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet app.yaml
