name: Deploy to App Engine

on:
  push:
    branches:
      - firebase-auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Cache Google Cloud SDK
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/google-cloud-sdk
          key: ${{ runner.os }}-gcloud-${{ hashFiles('**/google-cloud-sdk/VERSION') }}

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=<(echo "${{ secrets.APPLICATION_CREDENTIALS }}")
          gcloud config set project ${{ secrets.GCLOUD_PROJECT }}
          gcloud components update --quiet

      - name: Install dependencies
        run: npm ci

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet app.yaml
